/**
 * Tailwind CSS Preset — DesignSeed
 * Generated by DesignSeed (https://designseed.app)
 * Do not edit manually. Changes will be overwritten on next sync.
 *
 * Semantic classes available:
 *   Colors:  bg-action-primary, text-primary, bg-surface-default, ...
 *   Radius:  rounded-ds-lg, rounded-ds-xl, ...
 *   Spacing: p-card-padding, gap-gap-v, gap-gap-h, ...
 *   Shadow:  shadow-ds-md, shadow-ds-card, ...
 *   Font:    font-ds-heading, font-ds-body, text-ds-heading, ...
 *
 * Usage in tailwind.config.js:
 *   const designSeedPreset = require('./tailwind.preset.js');
 *   module.exports = { presets: [designSeedPreset], ... }
 */

module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "background": {
          "DEFAULT": "#545454"
        },
        "primary": {
          "400": "#E1F487",
          "500": "#D9F166",
          "600": "#D1EE45",
          "700": "#c9eb24"
        },
        "secondary": {
          "400": "#EFC7D6",
          "500": "#E99AB7",
          "600": "#E76998",
          "700": "#E93477"
        },
        "tertiary": {
          "400": "#CC93F3",
          "500": "#BF75F0",
          "600": "#B158EC",
          "700": "#a33ae9"
        },
        "danger": {
          "400": "#F49898",
          "500": "#F67570",
          "600": "#F64C4C",
          "700": "#EC2030"
        },
        "warning": {
          "400": "#FFD082",
          "500": "#FFC626",
          "600": "#FFAD00",
          "700": "#FE8E06"
        },
        "success": {
          "400": "#97D4B4",
          "500": "#68C487",
          "600": "#47B88B",
          "700": "#00C561"
        },
        "info": {
          "400": "#93C6FF",
          "500": "#4BA1FF",
          "600": "#3B82F6",
          "700": "#3A70F2"
        },
        "neutrals": {
          "50": "#FAFAFA",
          "100": "#F5F5F5",
          "200": "#E5E5E5",
          "300": "#D4D4D4",
          "400": "#A3A3A3",
          "500": "#737373",
          "600": "#525252",
          "700": "#333333",
          "800": "#1F1F1F",
          "900": "#111111"
        },
        "action-primary": "var(--color-action-primary)",
        "action-secondary": "var(--color-action-secondary)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-neutral": "var(--color-text-neutral)",
        "bg-primary": "var(--color-background-primary)",
        "bg-secondary": "var(--color-background-secondary)",
        "surface-default": "var(--color-surface-default)",
        "surface-raised": "var(--color-surface-raised)",
        "status-danger": "var(--color-status-danger)",
        "status-danger-bg": "var(--color-status-danger-bg)",
        "status-success": "var(--color-status-success)",
        "status-success-bg": "var(--color-status-success-bg)",
        "status-warning": "var(--color-status-warning)",
        "status-warning-bg": "var(--color-status-warning-bg)",
        "border-default": "var(--border-card-color)"
      },
      "borderRadius": {
        "lg": "12px",
        "md": "8px",
        "sm": "4px",
        "xl": "16px",
        "xs": "2px",
        "2xl": "24px",
        "none": "0px",
        "ds-sm": "var(--radius-sm)",
        "ds-md": "var(--radius-md)",
        "ds-lg": "var(--radius-lg)",
        "ds-xl": "var(--radius-xl)"
      },
      "fontFamily": {
        "heading": [
          "Manrope",
          "sans-serif"
        ],
        "body": [
          "Inter",
          "sans-serif"
        ],
        "ds-heading": "var(--font-heading)",
        "ds-body": "var(--font-body)"
      },
      "fontSize": {
        "ds-heading": "var(--font-size-heading)",
        "ds-subheading": "var(--font-size-subheading)",
        "ds-body": "var(--font-size-body)",
        "ds-label": "var(--font-size-label)"
      },
      "spacing": {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "card-padding": "var(--spacing-card-padding)",
        "gap-v": "var(--spacing-gap-vertical)",
        "gap-h": "var(--spacing-gap-horizontal)",
        "container": "var(--spacing-container)"
      },
      "boxShadow": {
        "ds-sm": "var(--shadow-sm)",
        "ds-md": "var(--shadow-md)",
        "ds-lg": "var(--shadow-lg)",
        "ds-xl": "var(--shadow-xl)",
        "ds-card": "var(--elevation-card)",
        "ds-popover": "var(--elevation-popover)",
        "ds-modal": "var(--elevation-modal)"
      }
    }
  }
};
