/**
 * Righteous Theme Configuration
 * Generated by DesignSeed (https://designseed.app)
 * Do not edit manually. Changes will be overwritten on next sync.
 */

export const theme = {
  "colors": {
    "background": {
      "primary": "#ffffff",
      "secondary": "#f9fafb"
    },
    "primary": {
      "400": "#B8CDEC",
      "500": "#89B0E8",
      "600": "#5793E7",
      "700": "#2074EB"
    },
    "secondary": {
      "400": "#F1C3D6",
      "500": "#EC95B9",
      "600": "#EC629B",
      "700": "#F12A7D"
    },
    "tertiary": {
      "400": "#C2E9A6",
      "500": "#A5E676",
      "600": "#86E841",
      "700": "#69E610"
    },
    "danger": {
      "400": "#F49898",
      "500": "#F67570",
      "600": "#F64C4C",
      "700": "#EC2030"
    },
    "warning": {
      "400": "#FFD082",
      "500": "#FFC626",
      "600": "#FFAD00",
      "700": "#FE8E06"
    },
    "success": {
      "400": "#97D4B4",
      "500": "#68C487",
      "600": "#47B88B",
      "700": "#00C561"
    },
    "info": {
      "400": "#93C6FF",
      "500": "#4BA1FF",
      "600": "#3B82F6",
      "700": "#3A70F2"
    },
    "neutrals": {
      "50": "#FAFAFA",
      "100": "#F5F5F5",
      "200": "#E5E5E5",
      "300": "#D4D4D4",
      "400": "#A3A3A3",
      "500": "#737373",
      "600": "#525252",
      "700": "#333333",
      "800": "#1F1F1F",
      "900": "#111111"
    },
    "text": {
      "primary": "#000000",
      "secondary": "#6B6B6B",
      "neutral": "#9B9B9B"
    }
  },
  "typography": {
    "body": {
      "fontFamily": "Montserrat",
      "fontSize": "18px",
      "fontWeight": 500,
      "lineHeight": 1.4
    },
    "label": {
      "fontFamily": "Montserrat",
      "fontSize": "14px",
      "fontWeight": 600,
      "lineHeight": 1.4
    },
    "button": {
      "fontFamily": "Montserrat",
      "fontSize": "16px",
      "fontWeight": 600,
      "lineHeight": 1.4
    },
    "heading": {
      "fontFamily": "Righteous",
      "fontSize": "40px",
      "fontWeight": 600,
      "lineHeight": 1.4
    },
    "paragraph": {
      "fontFamily": "Montserrat",
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": 1.4
    },
    "subheading": {
      "fontFamily": "Righteous",
      "fontSize": "24px",
      "fontWeight": 600,
      "lineHeight": 1.4
    }
  },
  "radius": {
    "lg": "12px",
    "md": "8px",
    "sm": "4px",
    "xl": "16px",
    "xs": "2px",
    "2xl": "24px",
    "none": "0px"
  },
  "spacing": {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "2xl": "48px",
    "cardPadding": "24px",
    "buttonPaddingX": "16px",
    "buttonPaddingY": "16px",
    "gapHorizontal": "12px",
    "gapVertical": "12px"
  },
  "shadows": {
    "none": "none",
    "sm": "0 1px 2px rgba(0,0,0,0.05)",
    "md": "0 4px 6px rgba(0,0,0,0.07)",
    "lg": "0 10px 15px rgba(0,0,0,0.1)",
    "xl": "0 20px 25px rgba(0,0,0,0.15)"
  },
  "buttons": {
    "icon": {
      "background": "transparent",
      "text": "#000000",
      "borderRadius": "8px",
      "hover": {
        "text": "#000000",
        "background": "#F4F4F5",
        "borderColor": "#000000"
      },
      "active": {
        "text": "#000000",
        "background": "#E4E4E7",
        "borderColor": "#000000"
      },
      "disabled": {
        "text": "#5a5a5a",
        "background": "transparent",
        "borderColor": "#6c6c6c"
      }
    },
    "link": {
      "background": "transparent",
      "text": "#E76998",
      "borderRadius": "0px",
      "hover": {
        "text": "#E76998",
        "background": "#F4F4F5",
        "borderColor": "#000000"
      },
      "active": {
        "text": "#E76998",
        "background": "#E4E4E7",
        "borderColor": "#000000"
      },
      "disabled": {
        "text": "#ce8fa6",
        "background": "transparent",
        "borderColor": "#6c6c6c"
      }
    },
    "ghost": {
      "background": "transparent",
      "text": "#000000",
      "borderRadius": "8px",
      "hover": {
        "text": "#000000",
        "background": "#F4F4F5",
        "borderColor": "#000000"
      },
      "active": {
        "text": "#000000",
        "background": "#E4E4E7",
        "borderColor": "#000000"
      },
      "disabled": {
        "text": "#5a5a5a",
        "background": "transparent",
        "borderColor": "#6c6c6c"
      }
    },
    "outline": {
      "background": "transparent",
      "text": "#000000",
      "borderRadius": "8px",
      "hover": {
        "text": "#000000",
        "background": "#F4F4F5",
        "borderColor": "#000000"
      },
      "active": {
        "text": "#000000",
        "background": "#E4E4E7",
        "borderColor": "#000000"
      },
      "disabled": {
        "text": "#5a5a5a",
        "background": "transparent",
        "borderColor": "#6c6c6c"
      }
    },
    "primary": {
      "background": "#c9eb24",
      "text": "#111111",
      "borderRadius": "8px",
      "hover": {
        "text": "#111111",
        "background": "#b5d420",
        "borderColor": "#000000"
      },
      "active": {
        "text": "#111111",
        "background": "#a1bc1d",
        "borderColor": "#000000"
      },
      "disabled": {
        "text": "#636363",
        "background": "#bfd06c",
        "borderColor": "#6c6c6c"
      }
    },
    "secondary": {
      "background": "#E93477",
      "text": "#FAFAFA",
      "borderRadius": "8px",
      "hover": {
        "text": "#FAFAFA",
        "background": "#ec528b",
        "borderColor": "#262626"
      },
      "active": {
        "text": "#FAFAFA",
        "background": "#d22f6b",
        "borderColor": "#000000"
      },
      "disabled": {
        "text": "#d7d7d7",
        "background": "#cf7496",
        "borderColor": "#6c6c6c"
      }
    },
    "destructive": {
      "background": "#DC2626",
      "text": "#FFFFFF",
      "borderRadius": "8px",
      "hover": {
        "text": "#FFFFFF",
        "background": "#e14747",
        "borderColor": "#262626"
      },
      "active": {
        "text": "#FFFFFF",
        "background": "#c62222",
        "borderColor": "#000000"
      },
      "disabled": {
        "text": "#dadada",
        "background": "#c86d6d",
        "borderColor": "#6c6c6c"
      }
    }
  }
} as const;

export type Theme = typeof theme;
export default theme;
